---
- name: Gather apt package facts.
  package_facts:
    manager: apt

- name: Update apt cache if WireGuard is not yet installed.
  apt: update_cache=yes
  when: '"wireguard" not in ansible_facts.packages'

- name: Install WireGuard package.
  apt:
    name: wireguard
    state: present

# DO we need to stop wireguard before any further config?
